language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer require symfony/framework-bundle:dev-master --prefer-source
  - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - travis-ci@liip.ch
