language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
matrix:
    allow_failures:
        - php: hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

before_script:
  - yes '' | pecl -q install -f mongo
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source

script: ./bin/phpunit --coverage-text

notifications:
  email:
    - travis-ci@liip.ch

matrix:
  allow_failures:
      - env: SYMFONY_VERSION=2.5.*
