language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - php composer.phar require symfony/symfony:2.1.*

script: phpunit --coverage-text

notifications:
  email:
    - travis-ci@liip.ch
